#include <math.h>
#include "control.h"
#include "pico/stdlib.h"
#include <stdio.h>
#include <string.h>
#include "samplerate.h"
#include "dsp_param.h"
#include "wavetable.h"
#include "dsp_control.h"
#include "shifter.pio.h"  // auto-generated by pioasm
#include "hardware/irq.h"
#include "hardware/pwm.h"
#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/pio.h"

// INTERFACE
// GPIO 15  - PB3 (Latch)
// GPIO 14 -  PB4 (CS)
// GPIO 13  - CB1 (Clock)
// GPIO 12  - CB2 (Data)

//#define LED_PIN 25
//#define DEBUG_PIN 22
#define LATCH_PIN 15
#define LATCH_MASK (1<<LATCH_PIN)
#define CS_PIN 14
#define CLK_PIN 13
#define DATA_PIN 12
#define interface_pio pio1

static DspControl *dspc; 
static int dma_channel;
static int sm;
static char *receive_buffer;

static volatile int received_count;
static volatile bool data_received;

static inline void reset_pio() {
    pio_sm_set_enabled(interface_pio, sm, false);
    pio_sm_clear_fifos(interface_pio, sm);
    pio_sm_restart(interface_pio, sm);
    pio_sm_exec(interface_pio, sm, pio_encode_mov(pio_isr, pio_null));  // <-- clear ISR
    pio_sm_set_enabled(interface_pio, sm, true);
}

void cs_pin_irq_handler(uint gpio, uint32_t events) {
    if (gpio == LATCH_PIN) {
        dspc_latch();
        return;
    }
    // This runs on pin change
    if (events & GPIO_IRQ_EDGE_RISE) {        
        dma_channel_abort(dma_channel);
        dma_channel_set_write_addr(dma_channel, receive_buffer, false);
        dma_channel_set_trans_count(dma_channel, sizeof(SynthRegisters), true);        
    } else if (events & GPIO_IRQ_EDGE_FALL) {
        dma_channel_abort(dma_channel);
        while (dma_channel_is_busy(dma_channel)) {
            tight_loop_contents();
        }  // fence
        received_count = (int)(dma_hw->ch[dma_channel].write_addr - (uintptr_t)receive_buffer);
        //data_received = true;
        reset_pio();
        dspc_transform(dspc);
    }
}

void setup_input_pio() {
    sm = pio_claim_unused_sm(interface_pio, true);
    uint offset = pio_add_program(interface_pio, &shifter_program);

    // Map DATA to in_base, and CLK to jmp_pin
    pio_gpio_init(interface_pio, DATA_PIN);
    pio_sm_set_consecutive_pindirs(interface_pio, sm, DATA_PIN, 1, false); // input
    pio_gpio_init(interface_pio, CLK_PIN);
    pio_sm_set_consecutive_pindirs(interface_pio, sm, CLK_PIN,  1, false); // input

    pio_sm_config sm_config = shifter_program_get_default_config(offset);
    sm_config_set_in_pins(&sm_config, DATA_PIN);       // IN reads from DATA_PIN
    sm_config_set_jmp_pin(&sm_config, CLK_PIN);        // wait pin = CLK_PIN

    // Shift: right, autopush every 8 bits
    sm_config_set_in_shift(&sm_config, false, true, 8);

    // Run at system clock (we’re externally clocked by wait on CLK edges)
    pio_sm_init(interface_pio, sm, offset, &sm_config);
    reset_pio();
}

void setup_input_dma() {
    // Setup DMA to automatically store shifted bytes
    dma_channel = dma_claim_unused_channel(true);
    dma_channel_config dma_config = dma_channel_get_default_config(dma_channel);
    channel_config_set_read_increment(&dma_config, false);  // from PIO RX FIFO
    channel_config_set_write_increment(&dma_config, true);  // to RAM buffer
    channel_config_set_transfer_data_size(&dma_config, DMA_SIZE_8);  // <-- bytes    
    channel_config_set_dreq(&dma_config, DREQ_PIO1_RX0);    // your SM
    channel_config_set_high_priority(&dma_config, false);

    // (optional) channel_config_set_high_priority(&c, false);
    dma_channel_configure(dma_channel, &dma_config, NULL, &interface_pio->rxf[sm], 0, false);
}

void setup_input_irq() {
    // IRQ for CS pin
    gpio_set_irq_enabled_with_callback(
        CS_PIN,
        GPIO_IRQ_EDGE_RISE | GPIO_IRQ_EDGE_FALL,
        true,
        &cs_pin_irq_handler
    );      
    gpio_set_irq_enabled(
        LATCH_PIN,
        GPIO_IRQ_EDGE_RISE,
        true);        
}

void control_init() {
    dspc = dspc_singleton();
    dspc_init(dspc);
    receive_buffer =  (char*)&dspc->registers;
    gpio_init(CS_PIN);          
    gpio_set_dir(CS_PIN, GPIO_IN);
    gpio_init(DATA_PIN);
    gpio_set_dir(DATA_PIN, GPIO_IN);
    gpio_init(CLK_PIN);
    gpio_set_dir(CLK_PIN, GPIO_IN);
    gpio_init(LATCH_PIN);
    gpio_set_dir(LATCH_PIN, GPIO_IN);
    gpio_set_pulls(CLK_PIN, true, false);   // pull-up on CB1 / clock
    gpio_set_pulls(DATA_PIN, true, false);  // pull-up on CB2 / data
    gpio_set_pulls(CS_PIN,  false, true);    
    /*gpio_init(PICO_DEFAULT_LED_PIN);
    gpio_set_dir(PICO_DEFAULT_LED_PIN, GPIO_OUT);*/

    setup_input_pio();
    //setup_input_dma();
    //setup_input_irq();

    irq_set_priority(DMA_IRQ_0,    0);
    irq_set_priority(TIMER_IRQ_0,  1);    
    irq_set_priority(USBCTRL_IRQ,  3);
}

static void __not_in_flash_func(drain_rx)() {
    bool last_cs = gpio_get(CS_PIN);
    bool last_latch = gpio_get(LATCH_PIN);
    uint8_t ptr = 0;
    while (true) {     
        bool latch = gpio_get(LATCH_PIN);
        if (latch && !last_latch) {
            dspc_latch();
        }
        bool cs = gpio_get(CS_PIN);
        if (cs) {
            if (!last_cs) {
                ptr = 0;
            }
            if (!pio_sm_is_rx_fifo_empty(interface_pio, sm)) {
                uint32_t data = pio_sm_get(interface_pio, sm);
                receive_buffer[ptr++] = (uint8_t)data;
            }
        } else if (last_cs) {
            dspc_transform(dspc);
            /*for (int i = 0; i < ptr; i++) {
                printf("%02x ", receive_buffer[i]);
            }
            printf("\n");
            stdio_flush();*/
        }
        last_cs = cs;
        last_latch = latch;
        tight_loop_contents();
    }
}

void control_run() {
    drain_rx();
}
