#include <math.h>
#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/pio.h"
#include "mcp4822.pio.h"  // auto-generated by pioasm
#include "synth.h"
#include "samplerate.h"
#include "voice.h"
#include "dsp_param.h"

#define PIN_CS 17
#define PIN_SCK 18
#define PIN_MOSI 19

#define FREQ 440.0f

#define LED_PIN 25
#define DEBUG_PIN 22

static int dma_channel;
static uint16_t buffer[2][BUF_LEN];
static volatile uint8_t next_buffer = 1;
static volatile bool data_requested = false;

static uint32_t dsp_control_id;

// For ADSR
static uint16_t env_table[ENVELOPE_STEPS];

DspParam dsp_param;

static Voice voices[NUMBER_OF_VOICES];
static int64_t block_buffer[BUF_LEN];


// Build a 16-bit MCP4822 frame for channel A, gain 1×, active
static inline uint16_t mcp4822_frame(uint16_t v12) {
    v12 &= 0x0FFF;
    return (0 << 15) | (1 << 14) | (1 << 13) | (1 << 12) | v12;
}

static void copy_voice_control() {
    for (int voice = 0; voice < NUMBER_OF_VOICES; voice++) {
        voices[voice].voice_param.phase_add = dsp_param.channels[voice].phase_add;
        voices[voice].voice_param.table_weight = dsp_param.channels[voice].table_weight;
        voices[voice].voice_param.volume = dsp_param.channels[voice].volume;
        voices[voice].voice_param.attack = dsp_param.channels[voice].attack;
        voices[voice].voice_param.decay = dsp_param.channels[voice].decay;
        voices[voice].voice_param.sustain = dsp_param.channels[voice].sustain;
        voices[voice].voice_param.release = dsp_param.channels[voice].release;
        voices[voice].voice_param.wavetable = dsp_param.channels[voice].wavetable;
        voices[voice].voice_param.wavetable2 = dsp_param.channels[voice].wavetable2;
        voices[voice].voice_param.pwm = dsp_param.channels[voice].pwm << 24;
        voices[voice].voice_param.use_pwm = dsp_param.channels[voice].waveform == WAV_SQUARE;
        voices[voice].voice_param.use_noise = dsp_param.channels[voice].waveform == WAV_NOISE;
        voices[voice].noise.phase_inc = dsp_param.channels[voice].noise_phase_inc;
        voices[voice].voice_param.highpass = dsp_param.channels[voice].highpass;
        voices[voice].voice_param.gate = dsp_param.channels[voice].gate;
    }
}

static inline bool is_gate_on(Voice *voice) {
    return (voice->voice_param.gate && !voice->last_gate);
}

static inline bool is_gate_off(Voice *voice) {
    return (!voice->voice_param.gate && voice->last_gate);
}

static inline void update_adsr(Voice *voice) {
    if (is_gate_on(voice)) {
        voice->ramp.target = 0 << ENVELOPE_FRACTIONAL_BITS;
        voice->ramp.remaining = voice->voice_param.release;
        voice->ramp.current = 65535 << ENVELOPE_FRACTIONAL_BITS;
        voice->ramp.step = (voice->ramp.target - voice->ramp.current) / voice->ramp.remaining;
    }
    voice->last_gate = voice->voice_param.gate;
}

static void fill_buffer(uint16_t *buffer, uint16_t buffer_size) {

    uint16_t buffer_offset = 0;    
    uint32_t current_id = atomic_load_explicit(&dsp_param.control_id, memory_order_acquire);
    if (dsp_control_id != current_id)  {
        copy_voice_control();
        dsp_control_id = current_id;
    }
    for (int v = 0; v < NUMBER_OF_VOICES; v++) {
        update_adsr(&voices[v]);

        for (int sample = 0; sample < buffer_size; sample++) {
            int64_t amp = (int64_t)synth_next_sample(&voices[v]);
            if (v > 0) {
                block_buffer[sample] += amp;
            } else {
                block_buffer[sample] = amp;
            }
        }
    }
    //bool clipping = false;
    for (int sample = 0; sample < buffer_size; sample++) {
        // TODO: Add dithering and all the sick stuff here
        int64_t amp = block_buffer[sample] >> (20 + VOICE_DOWN_MIX_BITS);  // 32 lovely bits down to 12
        if (amp < -2047) {
            amp = -2047;
            //clipping = true;
        } else if (amp > 2047) {
            amp = 2047;
            //clipping = true;
        }
        buffer[buffer_offset] = mcp4822_frame(amp + 2048);
        buffer_offset++;
    }
    //gpio_put(LED_PIN, clipping);
}

static void __isr dma_handler() {
    uint32_t flags = dma_hw->ints0;
    dma_hw->ints0 = flags;  // clear all that fired
    //dma_hw->ints0 = 1u << dma_channel;  // clear interrupt flag
    uint8_t filled_buffer = next_buffer;
    next_buffer = 1  - next_buffer; // swap which buffer is playing
    data_requested = true;       // signal CPU to refill the other one

    dma_channel_set_read_addr(dma_channel, buffer[filled_buffer], true);  // restart DMA
}


static void setup_audio_stream() {
    // ----- PIO setup -----
    PIO pio = pio0;
    uint sm = pio_claim_unused_sm(pio, true);
    uint off = pio_add_program(pio, &mcp4822_program);

    pio_sm_config c = mcp4822_program_get_default_config(off);
    sm_config_set_out_pins(&c, PIN_MOSI, 1);
    sm_config_set_sideset_pins(&c, PIN_CS);             // sideset base = CS
    sm_config_set_out_shift(&c, false, true, 16);       // MSB-first, autopull 16
    float div = clock_get_hz(clk_sys) / (SAMPLE_RATE * 53); // PIO Clock cycles per sample times sample rate
    sm_config_set_clkdiv(&c, div);

    pio_gpio_init(pio, PIN_MOSI);
    pio_gpio_init(pio, PIN_CS);
    pio_gpio_init(pio, PIN_SCK);
    pio_sm_set_consecutive_pindirs(pio, sm, PIN_MOSI, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, PIN_CS, 2, true);  // CS,SCK outputs
    pio_sm_init(pio, sm, off, &c);
    pio_sm_set_enabled(pio, sm, true);

    // DMA
    int dma_a = dma_claim_unused_channel(true);
    int dma_b = dma_claim_unused_channel(true);

    dma_channel_config ca = dma_channel_get_default_config(dma_a);
    channel_config_set_transfer_data_size(&ca, DMA_SIZE_16);
    channel_config_set_dreq(&ca, DREQ_PIO0_TX0);
    channel_config_set_chain_to(&ca, dma_b);  // after A → trigger B
    channel_config_set_read_increment(&ca, true);
    channel_config_set_write_increment(&ca, false);
    
    dma_channel_config cb = dma_channel_get_default_config(dma_b);
    channel_config_set_transfer_data_size(&cb, DMA_SIZE_16);
    channel_config_set_dreq(&cb, DREQ_PIO0_TX0);
    channel_config_set_chain_to(&cb, dma_a);  // after B → trigger A
    channel_config_set_read_increment(&cb, true);
    channel_config_set_write_increment(&cb, false);

    dma_channel_configure(dma_a, &ca, &pio0->txf[sm], buffer[0], BUF_LEN, false);
    dma_channel_configure(dma_b, &cb, &pio0->txf[sm], buffer[1], BUF_LEN, false);

    fill_buffer(buffer[0], BUF_LEN);
    dma_start_channel_mask(1u << dma_a);
    next_buffer = 1;
    data_requested = true;
    
    dma_channel_set_irq0_enabled(dma_a, true);
    dma_channel_set_irq1_enabled(dma_b, true);
    irq_set_exclusive_handler(DMA_IRQ_0, dma_handler);
    irq_set_enabled(DMA_IRQ_0, true);
}


static void init_env_table() {
    float db_divisor = (float)ENVELOPE_STEPS/64.0f;
    float amp_scale = ENVELOPE_SCALE-1;
    for (int i = 0; i < ENVELOPE_STEPS; i++) {
        float dbfs = -(float)(ENVELOPE_STEPS - 1 - i) / db_divisor;
        float level = amp_scale * powf(10, dbfs / 20.0);
        env_table[i] = (uint16_t)level;
    }
    env_table[0] = 0;
    //env_table[ENVELOPE_STEPS-1] = 1023;
}

void dsp_run() {    
    gpio_init(LED_PIN);
    gpio_set_dir(LED_PIN, GPIO_OUT);
    gpio_init(DEBUG_PIN);
    gpio_set_dir(DEBUG_PIN, GPIO_OUT);

    init_env_table();
    for (int i = 0; i < NUMBER_OF_VOICES; i++) {
        copy_voice_control(i);
        synth_init(&voices[i], env_table);
    }
    setup_audio_stream();
    while (true) {
        if (data_requested) {
            data_requested = false;
            fill_buffer(buffer[next_buffer], BUF_LEN);
        }
        tight_loop_contents();  // small wait hint
    }
}
