import math
from datetime import datetime

wavetable_size = 2048
wavetable_count = 8
wavetable_notes_per_table_shift = 4
wavetable_notes_per_table = (1<<wavetable_notes_per_table_shift)


def get_wavetable_square(index,base_frequency):
    x = index / wavetable_size
    s = 0.0
    harm = 1.0
    while harm * base_frequency < 20000.0:    
        s = s + math.sin(harm * 2.0 * math.pi * x) / harm
        harm += 2.0
    
    if s < -1:
        s = -1
    elif s > 1:
        s = 1
    return int(round(s * 32767))

def get_wavetable_saw(index,base_frequency):
    x = index / wavetable_size
    s = 0.0
    harm = 1.0
    sign = -1.0
    while harm * base_frequency < 20000.0:    
        s = s + sign * math.sin(harm * 2.0 * math.pi * x) / harm
        harm = harm + 1
        sign = -sign
    s = -2.0 * s / math.pi
    
    if s < -1:
        s = -1
    elif s > 1:
        s = 1
    return int(round(s * 32767))


def create_wavetable(base_frequency):
    print("{")
    for i in range(wavetable_size):
        n = (i+1) & (wavetable_size-1)
        u1 = get_wavetable_saw(i, base_frequency) & 0xffff
        u2 = get_wavetable_saw(n, base_frequency) & 0xffff
        u = (u1 | (u2<<16))
        print('0x{:08x}, '.format(u), end="")        
        if (i&7) == 7:
            print()
    print("},")

def create_wavetables():
    now = datetime.now()
    print('// wavetable_data.c - autogenerated by gentables.py in ' + now.strftime("%Y-%m-%d %H:%M:%S")+'\n')
    print('#include "wavetable_data.h"\n')
    print('const uint32_t wavetables[WAVETABLE_COUNT][WAVETABLE_SIZE] = {')
    note = 0
    for table in range(wavetable_count):
        base_frequency = 440.0 * pow(2.0, (note-69)/12.0)
        print('// Table {:d}, base frequency {:f}'.format(table, base_frequency))
        create_wavetable(base_frequency)
        note += wavetable_notes_per_table
    print('};')
    #print('#endif')

def main():    
    create_wavetables()

if __name__ == "__main__":
    main()



