import math
import sys
from datetime import datetime

wavetable_size = 2048
wavetable_count = 8
wavetable_notes_per_table_shift = 4
wavetable_notes_per_table = (1<<wavetable_notes_per_table_shift)

def get_wavetable_triangle(index, base_frequency):
    x = index / wavetable_size
    s = 0.0
    harm = 1.0
    sign = 1.0
    while harm * base_frequency < 20000.0:    
        s = s + sign * math.sin(harm * 2.0 * math.pi * x) / (harm * harm)
        harm = harm + 2
        sign = -sign
    s = -2.0 * s / math.pi
    
    if s < -1:
        s = -1
    elif s > 1:
        s = 1
    return int(round(s * 32767))


def get_wavetable_square(index,base_frequency):
    x = index / wavetable_size
    s = 0.0
    harm = 1.0
    while harm * base_frequency < 20000.0:    
        s = s + math.sin(harm * 2.0 * math.pi * x) / harm
        harm += 2.0
    
    if s < -1:
        s = -1
    elif s > 1:
        s = 1
    return int(round(s * 32767))

def get_wavetable_saw(index,base_frequency):
    x = index / wavetable_size
    s = 0.0
    harm = 1.0
    sign = -1.0
    while harm * base_frequency < 20000.0:    
        s = s + sign * math.sin(harm * 2.0 * math.pi * x) / harm
        harm = harm + 1
        sign = -sign
    s = -2.0 * s / math.pi
    
    if s < -1:
        s = -1
    elif s > 1:
        s = 1
    return int(round(s * 32767))


def create_wavetable(base_frequency, wave_func):
    print("{")
    for i in range(wavetable_size):
        n = (i+1) & (wavetable_size-1)
        u1 = wave_func(i, base_frequency) & 0xffff
        u2 = wave_func(n, base_frequency) & 0xffff
        u = (u1 | (u2<<16))
        print('0x{:08x}, '.format(u), end="")        
        if (i&7) == 7:
            print()
    print("},")

def create_wavetables(wave_func,waveform):
    now = datetime.now()
    print('// wavetable_{}.c - autogenerated by gentables.py in '.format(waveform) + now.strftime("%Y-%m-%d %H:%M:%S")+'\n')
    print('#include "wavetable_{}.h"\n'.format(waveform))
    print('const uint32_t wavetables_{}[WAVETABLE_COUNT][WAVETABLE_SIZE] = {{'.format(waveform))
    note = 0
    for table in range(wavetable_count):
        base_frequency = 440.0 * pow(2.0, (note-69)/12.0)
        print('// Table {:d}, base frequency {:f}'.format(table, base_frequency))
        create_wavetable(base_frequency, wave_func)
        note += wavetable_notes_per_table
    print('};')
    #print('#endif')

def print_usage():
    print('Usage {} <square|saw|triangle>'.format(sys.argv[0]))

def main():    
    if len(sys.argv) < 2:
        print_usage()
        exit(1)
    
    waveform = sys.argv[1]
    if waveform == 'saw':        
        create_wavetables(get_wavetable_saw,'saw')
    elif waveform == 'square':
        create_wavetables(get_wavetable_square,'square')
    elif waveform == 'triangle':
        create_wavetables(get_wavetable_triangle,'triangle')
    else:
        print_usage()
        exit(1)

if __name__ == "__main__":
    main()



