#include <math.h>

#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/pio.h"
#include "mcp4822.pio.h"  // auto-generated by pioasm
#include "pico/stdlib.h"
#include "pico/multicore.h"
#include "samplerate.h"
#include "synth.h"

#define PIN_CS 17
#define PIN_SCK 18
#define PIN_MOSI 19

#define FREQ 440.0f
#define BUF_LEN 256

static int dma_channel;
static uint16_t buffer[2][BUF_LEN];
static volatile uint8_t next_buffer = 1;
static volatile bool data_requested = false;

// Build a 16-bit MCP4822 frame for channel A, gain 1×, active
static inline uint16_t mcp4822_frame(uint16_t v12) {
    v12 &= 0x0FFF;
    return (0 << 15) | (1 << 14) | (1 << 13) | (1 << 12) | v12;
}

void fill_buffer(uint16_t *buffer, uint16_t buffer_size) {
    for (uint16_t sample = 0; sample < buffer_size; sample++) {
        int32_t amp = synth_next_sample();
        // TODO: Add dithering and all the sick stuff here
        amp = amp >> 20;  // 32 lovely bits down to 12        

        buffer[sample] = mcp4822_frame(amp+2048);
    }
}

void __isr dma_handler() {
    uint32_t flags = dma_hw->ints0;
    dma_hw->ints0 = flags;  // clear all that fired
    //dma_hw->ints0 = 1u << dma_channel;  // clear interrupt flag
    uint8_t filled_buffer = next_buffer;
    next_buffer = 1  - next_buffer; // swap which buffer is playing
    data_requested = true;       // signal CPU to refill the other one

    dma_channel_set_read_addr(dma_channel, buffer[filled_buffer], true);  // restart DMA
}

void setup_audio_stream() {
    // ----- PIO setup -----
    PIO pio = pio0;
    uint sm = pio_claim_unused_sm(pio, true);
    uint off = pio_add_program(pio, &mcp4822_program);

    pio_sm_config c = mcp4822_program_get_default_config(off);
    sm_config_set_out_pins(&c, PIN_MOSI, 1);
    sm_config_set_sideset_pins(&c, PIN_CS);             // sideset base = CS
    sm_config_set_out_shift(&c, false, true, 16);       // MSB-first, autopull 16
    float div = clock_get_hz(clk_sys) / (SAMPLE_RATE * 53); // PIO Clock cycles per sample times sample rate
    sm_config_set_clkdiv(&c, div);

    pio_gpio_init(pio, PIN_MOSI);
    pio_gpio_init(pio, PIN_CS);
    pio_gpio_init(pio, PIN_SCK);
    pio_sm_set_consecutive_pindirs(pio, sm, PIN_MOSI, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, PIN_CS, 2, true);  // CS,SCK outputs
    pio_sm_init(pio, sm, off, &c);
    pio_sm_set_enabled(pio, sm, true);

    // DMA
    int dma_a = dma_claim_unused_channel(true);
    int dma_b = dma_claim_unused_channel(true);

    dma_channel_config ca = dma_channel_get_default_config(dma_a);
    channel_config_set_transfer_data_size(&ca, DMA_SIZE_16);
    channel_config_set_dreq(&ca, DREQ_PIO0_TX0);
    channel_config_set_chain_to(&ca, dma_b);  // after A → trigger B
    channel_config_set_read_increment(&ca, true);
    channel_config_set_write_increment(&ca, false);
    
    dma_channel_config cb = dma_channel_get_default_config(dma_b);
    channel_config_set_transfer_data_size(&cb, DMA_SIZE_16);
    channel_config_set_dreq(&cb, DREQ_PIO0_TX0);
    channel_config_set_chain_to(&cb, dma_a);  // after B → trigger A
    channel_config_set_read_increment(&cb, true);
    channel_config_set_write_increment(&cb, false);

    dma_channel_configure(dma_a, &ca, &pio0->txf[sm], buffer[0], BUF_LEN, false);
    dma_channel_configure(dma_b, &cb, &pio0->txf[sm], buffer[1], BUF_LEN, false);

    fill_buffer(buffer[0], BUF_LEN);
    dma_start_channel_mask(1u << dma_a);
    next_buffer = 1;
    data_requested = true;
    
    dma_channel_set_irq0_enabled(dma_a, true);
    dma_channel_set_irq1_enabled(dma_b, true);
    irq_set_exclusive_handler(DMA_IRQ_0, dma_handler);
    irq_set_enabled(DMA_IRQ_0, true);
}


#define TABLE_SIZE 256
static uint8_t sine_table[TABLE_SIZE];
void init_sine_table(void) {
    for (int i = 0; i < TABLE_SIZE; i++) {
        float x = (float)i / TABLE_SIZE;
        float s = sinf(2.0f * M_PI * x);        // -1.0 → +1.0
        sine_table[i] = (uint8_t)(128 + s * (63 - 1));
    }
}

volatile uint8_t g_volume = 127;
void core1_entry() {
    init_sine_table();
    uint8_t sinofs = 0;

    while (true) {
        g_volume = sine_table[sinofs++];
        sleep_ms(5);
    }
}

int main() {
    stdio_init_all();
    setup_audio_stream();
    multicore_launch_core1(core1_entry);
    while (true) {
        if (data_requested) {
            data_requested = false;
            fill_buffer(buffer[next_buffer], BUF_LEN);
        }
        tight_loop_contents();  // small wait hint
    }
}
