#include <math.h>

#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/pio.h"
#include "mcp4822.pio.h"  // auto-generated by pioasm
#include "pico/stdlib.h"

#define PIN_CS 17
#define PIN_SCK 18
#define PIN_MOSI 19

#define FS 48000.0f
#define FREQ 440.0f
#define BUF_LEN 256

static uint16_t frames[BUF_LEN];

// Build a 16-bit MCP4822 frame for channel A, gain 1×, active
static inline uint16_t mcp4822_frame(uint16_t v12) {
    v12 &= 0x0FFF;
    return (0 << 15) | (1 << 14) | (1 << 13) | (1 << 12) | v12;
}

int main() {
    stdio_init_all();

    // ----- Generate 440 Hz sine -----
    for (int i = 0; i < BUF_LEN; i++) {
        float s = sinf(2 * M_PI * FREQ * i / FS);
        uint16_t v = (uint16_t)((s * 0.5f + 0.5f) * 4095);
        frames[i] = mcp4822_frame(v);
    }

    // ----- PIO setup -----
    PIO pio = pio0;
    uint sm = pio_claim_unused_sm(pio, true);
    uint off = pio_add_program(pio, &mcp4822_program);

    pio_sm_config c = mcp4822_program_get_default_config(off);
    sm_config_set_out_pins(&c, PIN_MOSI, 1);
    sm_config_set_sideset_pins(&c, PIN_CS);             // sideset base = CS
    sm_config_set_out_shift(&c, false, true, 16);       // MSB-first, autopull 16
    float div = clock_get_hz(clk_sys) / (2e6f * 3.0f);  // ~2 MHz bit clock
    sm_config_set_clkdiv(&c, div);

    pio_gpio_init(pio, PIN_MOSI);
    pio_gpio_init(pio, PIN_CS);
    pio_gpio_init(pio, PIN_SCK);
    pio_sm_set_consecutive_pindirs(pio, sm, PIN_MOSI, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, PIN_CS, 2, true);  // CS,SCK outputs
    pio_sm_init(pio, sm, off, &c);
    pio_sm_set_enabled(pio, sm, true);

    // ----- DMA → PIO -----
    int chan = dma_claim_unused_channel(true);
    dma_channel_config dc = dma_channel_get_default_config(chan);
    channel_config_set_transfer_data_size(&dc, DMA_SIZE_16);
    channel_config_set_dreq(&dc, DREQ_PIO0_TX0);
    channel_config_set_read_increment(&dc, true);
    channel_config_set_write_increment(&dc, false);

    dma_channel_configure(chan, &dc, &pio->txf[sm], frames, BUF_LEN,
        true);  // start

    // Loop forever: restart DMA when buffer done
    while (true) {
        dma_channel_wait_for_finish_blocking(chan);
        dma_channel_set_read_addr(chan, frames, true);
    }
}
